# Generated by Django 4.0.3 on 2022-06-29 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finanza',
            fields=[
                ('id_fz', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='historial_mp',
            fields=[
                ('id_hp', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha')),
                ('materiap', models.CharField(max_length=50, verbose_name='Materia prima')),
            ],
        ),
        migrations.CreateModel(
            name='infofactura',
            fields=[
                ('id_if', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('entregado', models.IntegerField(verbose_name='Valor entregado')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('adiciones', models.CharField(max_length=50, verbose_name='Adiciones')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha')),
                ('id_ft', models.IntegerField(verbose_name='Factura')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='lugar',
            fields=[
                ('id_lg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='materia_p',
            fields=[
                ('id_mp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('unidad', models.CharField(max_length=10, verbose_name='unidad')),
                ('costo', models.IntegerField(verbose_name='costo')),
                ('costo_u', models.IntegerField(verbose_name='costo unitario')),
                ('proveedor', models.CharField(max_length=30, verbose_name='proveedor')),
                ('contacto', models.CharField(max_length=14, null=True, verbose_name='contacto')),
                ('tiempo', models.CharField(max_length=14, null=True, verbose_name='tiempo de entrega')),
                ('mincant', models.IntegerField(null=True, verbose_name='cantidad minima')),
                ('descripcion', models.TextField(max_length=100, null=True, verbose_name='descripcion')),
                ('estado', models.CharField(max_length=20, verbose_name='estado')),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha')),
                ('id_lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.lugar', verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='materia_s',
            fields=[
                ('id_ms', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('descripcion', models.TextField(max_length=100, verbose_name='descripcion')),
                ('estado', models.CharField(max_length=20, verbose_name='estado')),
                ('id_lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.lugar', verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_us', models.IntegerField(primary_key=True, serialize=False, verbose_name='Identificacion')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('ocupacion', models.CharField(max_length=20, verbose_name='Ocupacion')),
                ('usuario', models.CharField(default='id_us', max_length=20, verbose_name='Usuario')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
                ('lugar', models.CharField(max_length=20, verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_pd', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
                ('descripcion', models.TextField(max_length=100, null=True, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='Precio base')),
                ('id_lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.lugar', verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='posicion',
            fields=[
                ('id_ps', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('id_pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.producto', verbose_name='producto')),
            ],
        ),
        migrations.CreateModel(
            name='mezcla',
            fields=[
                ('id_mz', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('costo', models.IntegerField(verbose_name='costo')),
                ('id_mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.materia_p', verbose_name='materia primaria')),
                ('id_ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.materia_s', verbose_name='materia secundaria')),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id_mn', models.AutoField(primary_key=True, serialize=False)),
                ('id_ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.materia_s', verbose_name='materia secundaria')),
                ('id_ps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.posicion', verbose_name='posicion')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id_ft', models.AutoField(primary_key=True, serialize=False)),
                ('id_lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.lugar', verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='entregado',
            fields=[
                ('id_eg', models.AutoField(primary_key=True, serialize=False)),
                ('mesa', models.CharField(max_length=50)),
                ('cliente', models.CharField(max_length=50, null=True)),
                ('id_cr', models.CharField(max_length=50, verbose_name='carrito')),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('precio', models.IntegerField(null=True)),
                ('preciot', models.IntegerField(null=True)),
                ('id_lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.lugar', verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='candycarrito',
            fields=[
                ('id_cr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pd', models.CharField(max_length=20, null=True)),
                ('precio', models.IntegerField(null=True, verbose_name='precio')),
                ('id_lg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.lugar', verbose_name='Lugar')),
                ('id_pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.producto', verbose_name='producto')),
            ],
        ),
        migrations.CreateModel(
            name='armado',
            fields=[
                ('id_ar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ms', models.CharField(max_length=20, null=True)),
                ('precio', models.IntegerField(null=True)),
                ('id_cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.candycarrito', verbose_name='carrito')),
                ('id_mn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.menu', verbose_name='menu')),
            ],
        ),
    ]
