# Generated by Django 4.0.3 on 2022-06-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
