# Generated by Django 4.0.3 on 2022-07-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0002_remove_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id_sn', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
