# Generated by Django 4.0.3 on 2022-07-01 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0003_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='contraseña',
        ),
    ]
