# Generated by Django 4.0.3 on 2022-07-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0004_remove_signup_contraseña'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
