# Generated by Django 4.0.3 on 2022-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0005_delete_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_p',
            name='costo',
            field=models.FloatField(verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='materia_p',
            name='costo_u',
            field=models.FloatField(verbose_name='costo unitario'),
        ),
    ]
