# Generated by Django 4.0.3 on 2022-07-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0007_delete_finanza_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='finanza',
            fields=[
                ('id_fz', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=50, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='historial_fz',
            fields=[
                ('id_hf', models.AutoField(primary_key=True, serialize=False)),
                ('fz_id', models.IntegerField(verbose_name='Factura')),
            ],
        ),
    ]
