# Generated by Django 4.0.3 on 2022-07-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0008_finanza_historial_fz'),
    ]

    operations = [
        migrations.CreateModel(
            name='compt',
            fields=[
                ('id_cp', models.AutoField(primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=50, verbose_name='Servicio')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('hora', models.CharField(max_length=50, verbose_name='Hora')),
            ],
        ),
    ]
