# Generated by Django 4.0.3 on 2022-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0009_compt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compt',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='compt',
            name='costo',
            field=models.FloatField(default=0, verbose_name='Costo'),
            preserve_default=False,
        ),
    ]
