# Generated by Django 4.0.3 on 2022-07-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0010_remove_compt_cantidad_compt_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='compt',
            name='finz',
            field=models.IntegerField(default=2, verbose_name='Cantidad'),
            preserve_default=False,
        ),
    ]
