# Generated by Django 4.0.3 on 2022-07-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0011_compt_finz'),
    ]

    operations = [
        migrations.AddField(
            model_name='compt',
            name='lg',
            field=models.IntegerField(default=1, verbose_name='Lugar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finanza',
            name='lg',
            field=models.IntegerField(default=1, verbose_name='Lugar'),
            preserve_default=False,
        ),
    ]
