# Generated by Django 4.0.3 on 2022-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0013_rename_lg_compt_id_lg_rename_lg_finanza_id_lg'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_fz',
            name='fecha',
            field=models.CharField(default='3/07/2022', max_length=50, verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
