# Generated by Django 4.0.3 on 2022-07-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0014_historial_fz_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='finanza',
            name='costot',
            field=models.IntegerField(default=0, verbose_name='Costo total'),
            preserve_default=False,
        ),
    ]
