# Generated by Django 4.0.3 on 2022-07-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0015_finanza_costot'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_fz',
            name='costot',
            field=models.IntegerField(default=0, verbose_name='Costo total'),
            preserve_default=False,
        ),
    ]
