# Generated by Django 4.0.3 on 2022-07-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0019_alter_historial_fz_costot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finanza',
            name='costot',
            field=models.IntegerField(null=True, verbose_name='Costo total'),
        ),
    ]
