# Generated by Django 4.0.3 on 2022-07-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0020_alter_finanza_costot'),
    ]

    operations = [
        migrations.AddField(
            model_name='compt',
            name='id_sv',
            field=models.IntegerField(default=0, verbose_name='Servicio'),
            preserve_default=False,
        ),
    ]
