# Generated by Django 4.0.3 on 2022-07-04 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0021_compt_id_sv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_fz',
            name='costot',
            field=models.FloatField(null=True, verbose_name='Costo total'),
        ),
    ]
