# Generated by Django 4.0.3 on 2022-07-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0023_alter_armado_precio_alter_candycarrito_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='basepd',
            fields=[
                ('id_bp', models.AutoField(primary_key=True, serialize=False)),
                ('id_ms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.materia_s', verbose_name='Materia secundaria')),
                ('id_pd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candyapp.producto', verbose_name='Producto')),
            ],
        ),
    ]
