# Generated by Django 4.0.3 on 2022-07-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0024_basepd'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepd',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='cantidad'),
            preserve_default=False,
        ),
    ]
