# Generated by Django 4.0.3 on 2022-07-08 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0025_basepd_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepd',
            name='id_ms',
        ),
        migrations.AddField(
            model_name='basepd',
            name='id_mp',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='candyapp.materia_p', verbose_name='Materia'),
            preserve_default=False,
        ),
    ]
