# Generated by Django 4.0.3 on 2022-07-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candyapp', '0026_remove_basepd_id_ms_basepd_id_mp'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(default='Activo', max_length=20, verbose_name='estado'),
            preserve_default=False,
        ),
    ]
